schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: "Bearer 80d11ec5224e37d71cb08247d4c644"
        X-Exclude-Invalid: true
documents: './**/*.graphql'
generates:
  graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unknown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node